### PR TITLE
Feature: Allow commands to write to buffer

### PR DESCRIPTION
**Pull request by raaaahman**
## Purpose

This PR aims to allow more elaborate terminal commands. It does so by exporting the TerminalContext so developer are able to trigger bufferedContent state updates.

This should also permits terminal state to be manipulated from other React elements, like asked in #63 and #173

## Details

- Add type `TerminalShell` that represents the internal method to manipulate terminal state
- Export the `TerminalContext`to be manipulated by client code
- Change logic in the `useBufferedContent`hook, so the content written to the buffer during command execution is not overridden by the command's return value
- Add a new state variable to write content that displays only while the command is executing, and is removed immediately after execution is complete
- Add two example commands using these new features in example

## Going further

I'm actually a bit worried that the tests might not be very reliable. As the `useBufferedContent` hook triggers several state updates in a row, there's a difference in result whether we wrap the `writeText` call in an `act` callback and when we don't (see the tests that have been added). 

I'm not so sure if this is an issue or expected to work that way, but the React Testing Library specifies that users should not have to write `act` calls because both `fireEvent` and `userEvent` already do so internally.

By the way, how do you work on this library @bony2023 ? I had to create a project that incorporates it has a git submodule to be able to manually test it, and wasn't able to test the `example` app.

### CODE REVIEW

**Comment by raaaahman** [comment]
@bony2023, do you mind to run that job again? A 500 internal server error from GitHub Actions is probably not related to the code I wrote, especially since I didn't touch the GitHub workflows.

**Comment by bony2023** [comment]
@raaaahman Thanks for the PR. Just retried the job again! 

This looks good. I was actually thinking to have this kind of functionality where we expose these internals to build more custom flavours of terminal. 

> By the way, how do you work on this library
I just run the command `./node_modules/.bin/npm-install-peers` to install required peers for the project and then run the tests.

**Review by bony2023 — APPROVED** [review]

**Comment by raaaahman** [comment]
> This looks good. I was actually thinking to have this kind of functionality where we expose these internals to build more custom flavours of terminal.

Nice. I also thought about switching from useState to useReducer in the Terminal Context, and then expose the dispatch function for more flexibility, but I went with the simplest approach for this PR.

> I just run the command `./node_modules/.bin/npm-install-peers` to install required peers for the project and then run the tests.

Okay. I'm big on automated tests in general, but I'm not so confident in the tests from the testing library when it involves sequential state updates (when you run a command, state is updated once to display the waiting content, then a second time to show the command response). When developing this PR, I added a test that was passing while the feature was clearly not working in manual testing.

Would you think about using Yarn workspaces in order to set the library and the example app as a monorepo? It would make it pretty easy to manually test changes locally in addition to the test suite.

**Comment by bjoe87** [comment]
Any ETA on this? :) This would be great to have.

**Comment by RobinKuiper** [comment]
I would really love this functionality, is this something that is getting merged?

**Comment by XenonPy** [comment]
Yeah, maybe even a simple content prop so we could use something like const updatedContent = [...terminalContent, message];

**Comment by bony2023** [comment]
closes #63 #173

**Pull request merged**
